package view;

import controller.ConexaoDB;
import controller.ControllerCategoriaEventos;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import model.ModelCategoriaEventos;
import model.ModelTabela;


public class FrmCategoriaEventos extends javax.swing.JFrame {
    
     ConexaoDB conectaCategoriaEventos = new ConexaoDB();
     ModelCategoriaEventos mcateven = new ModelCategoriaEventos();
     ControllerCategoriaEventos controlCatEven = new ControllerCategoriaEventos();
     int flag = 0;
     
     

    /**
     * Creates new form FrmCategoriaEventos
     */
    public FrmCategoriaEventos() {
        initComponents();
        
        
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/ss.jpg")).getImage());
        
        //conectaCategoriaEventos.conexao();
        
        preencherTabelaCategoriaEventos("SELECT * FROM CATEGORIA_EVENTOS ORDER BY COD_CATEVEN");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        aaa = new javax.swing.JLabel();
        dddd = new javax.swing.JLabel();
        txtCodCatEven = new javax.swing.JTextField();
        txtNomedaCategoriaEvento = new javax.swing.JTextField();
        btnPesquisarCatEven = new javax.swing.JButton();
        txtCampoPesquisaCatEven = new javax.swing.JTextField();
        btnNovoCatEven = new javax.swing.JButton();
        btnSalvarCatEven = new javax.swing.JButton();
        btnAlterarCatEven = new javax.swing.JButton();
        btnExcluirCatEven = new javax.swing.JButton();
        btnCancelarCatEven = new javax.swing.JButton();
        btnSairCatEven = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCategoriaEventos = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Categoria de Eventos");
        setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        setResizable(false);

        aaa.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        aaa.setText("Cod:");

        dddd.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        dddd.setText("Nome da Categoria*:");

        txtCodCatEven.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCodCatEven.setEnabled(false);

        txtNomedaCategoriaEvento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomedaCategoriaEvento.setEnabled(false);

        btnPesquisarCatEven.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnPesquisarCatEven.setText("Buscar");
        btnPesquisarCatEven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarCatEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCatEvenActionPerformed(evt);
            }
        });

        txtCampoPesquisaCatEven.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnNovoCatEven.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnNovoCatEven.setText("Novo");
        btnNovoCatEven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoCatEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCatEvenActionPerformed(evt);
            }
        });

        btnSalvarCatEven.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnSalvarCatEven.setText("Salvar");
        btnSalvarCatEven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvarCatEven.setEnabled(false);
        btnSalvarCatEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCatEvenActionPerformed(evt);
            }
        });

        btnAlterarCatEven.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnAlterarCatEven.setText("Alterar");
        btnAlterarCatEven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarCatEven.setEnabled(false);
        btnAlterarCatEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCatEvenActionPerformed(evt);
            }
        });

        btnExcluirCatEven.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnExcluirCatEven.setText("Excluir");
        btnExcluirCatEven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirCatEven.setEnabled(false);
        btnExcluirCatEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCatEvenActionPerformed(evt);
            }
        });

        btnCancelarCatEven.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnCancelarCatEven.setText("Cancelar");
        btnCancelarCatEven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarCatEven.setEnabled(false);
        btnCancelarCatEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCatEvenActionPerformed(evt);
            }
        });

        btnSairCatEven.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnSairCatEven.setText("Sair");
        btnSairCatEven.setToolTipText("Fechar janela");
        btnSairCatEven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSairCatEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCatEvenActionPerformed(evt);
            }
        });

        jTableCategoriaEventos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableCategoriaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCategoriaEventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableCategoriaEventos.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jTableCategoriaEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCategoriaEventosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCategoriaEventos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(txtCampoPesquisaCatEven, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisarCatEven))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dddd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aaa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodCatEven, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomedaCategoriaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluirCatEven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarCatEven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovoCatEven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvarCatEven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterarCatEven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSairCatEven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnNovoCatEven)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarCatEven)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarCatEven)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirCatEven)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarCatEven)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSairCatEven))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aaa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodCatEven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dddd, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomedaCategoriaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPesquisarCatEven)
                            .addComponent(txtCampoPesquisaCatEven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(407, 314));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarCatEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCatEvenActionPerformed
         // BOTÃO PESQUISAR
        
        if ( txtCampoPesquisaCatEven.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Informe o nome para busca!");
            txtCampoPesquisaCatEven.requestFocusInWindow();
            
        } else if ( !txtCampoPesquisaCatEven.getText().isEmpty() ) {
           
        // ABILITANDO/DESABILITANDO OS BOTÕES ANTES DE PESQUISAR
        btnNovoCatEven.setEnabled(true);
        btnAlterarCatEven.setEnabled(!true);
        btnExcluirCatEven.setEnabled(!true);
        btnCancelarCatEven.setEnabled(!true);
        
        
        ModelCategoriaEventos modelCategoriaEventos = controlCatEven.buscarCategoriaEventos(mcateven);
        
        /*
        txtCodEventos.setText(String.valueOf(modelCategoriaEventos.getCod_cateven()));
        txtNomedaCategoriaEvento.setText(modelCategoriaEventos.getNome_cateven());
        */
        
        mcateven.setPesquisa(txtCampoPesquisaCatEven.getText());
        
        
        preencherTabelaCategoriaEventos("SELECT * FROM CATEGORIA_EVENTOS WHERE NOME_CATEVEN LIKE '%" + mcateven.getPesquisa() + "%'");
        
        
        txtCampoPesquisaCatEven.setText("");
        
        
        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS PESQUISAR
        btnNovoCatEven.setEnabled(true);
        btnAlterarCatEven.setEnabled(!true);
        btnSalvarCatEven.setEnabled(false);
        btnExcluirCatEven.setEnabled(!true);
        btnCancelarCatEven.setEnabled(!false);
        btnPesquisarCatEven.setEnabled(true);
        
        // DESABILITANDO OS CAMPOS APÓS PESQUISAR
        txtCodCatEven.setEnabled(false);
        txtNomedaCategoriaEvento.setEnabled(false);

        
        // LIMPANDO OS CAMOPS APÓS PESQUISAR
        txtCodCatEven.setText("");
        txtNomedaCategoriaEvento.setText("");
  
        
        
        } else if ( mcateven.getPesquisa().equals("")) {
            
            preencherTabelaCategoriaEventos("SELECT * FROM CATEGORIA_EVENTOS ORDER BY COD_CATEVEN");
        }
        
       // preencherTabelaUsuario("select * from  usuarios where nome_usuario like '%" + musuario.getPesquisa() + "%'");
       
    }//GEN-LAST:event_btnPesquisarCatEvenActionPerformed

    private void btnAlterarCatEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCatEvenActionPerformed
        // BOTÃO ALTERAR

        flag = 2;

        // ABILITANDO/DESABILITANDO OS CAMPOS
        txtNomedaCategoriaEvento.setEnabled(true);
        txtCampoPesquisaCatEven.setEnabled(false);

        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS CLICAR NO BOTÃO
        btnNovoCatEven.setEnabled(false);
        btnSalvarCatEven.setEnabled(true);
        btnAlterarCatEven.setEnabled(false);
        btnExcluirCatEven.setEnabled(false);
        btnCancelarCatEven.setEnabled(true);
        btnPesquisarCatEven.setEnabled(false);

        preencherTabelaCategoriaEventos("SELECT * FROM CATEGORIA_EVENTOS ORDER BY COD_CATEVEN");
        
        
    }//GEN-LAST:event_btnAlterarCatEvenActionPerformed

    private void btnSairCatEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCatEvenActionPerformed
        // BOTÃO SAIR
        
        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS CANCELAR
        btnNovoCatEven.setEnabled(true);
        btnAlterarCatEven.setEnabled(!true);
        btnSalvarCatEven.setEnabled(false);
        btnExcluirCatEven.setEnabled(!true);
        btnCancelarCatEven.setEnabled(false);
        btnPesquisarCatEven.setEnabled(true);

        // DESABILITANDO OS CAMPOS APÓS CANCELAR
        txtCodCatEven.setText("");
        txtNomedaCategoriaEvento.setEnabled(false);
        txtCampoPesquisaCatEven.setEnabled(true);

        // LIMPANDO OS CAMPOS APÓS CLICAR EM "NÃO" EXLCUIR
        txtCodCatEven.setText("");
        txtNomedaCategoriaEvento.setText("");
        txtCampoPesquisaCatEven.setText("");

        
        dispose();
        
        preencherTabelaCategoriaEventos("SELECT * FROM CATEGORIA_EVENTOS ORDER BY COD_CATEVEN");
        
        //conectaCategoriaEventos.desconecta();
        
        
    }//GEN-LAST:event_btnSairCatEvenActionPerformed

    private void btnNovoCatEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCatEvenActionPerformed
        // BOTÃO NOVO

        flag = 1;

        // LIMPANDO OS CAMPOS APÓS CLICAR
        txtCodCatEven.setText("");
        txtNomedaCategoriaEvento.setText("");
        txtCampoPesquisaCatEven.setText("");

        // ABILITANDO OS CAMPOS
        txtNomedaCategoriaEvento.setEnabled(true);
        txtCampoPesquisaCatEven.setEnabled(false);

        // COLOCANDO FOCO NOS CAMPOS
        txtNomedaCategoriaEvento.requestFocusInWindow();

        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS CLICAR NO BOTÃO
        btnNovoCatEven.setEnabled(false);
        btnAlterarCatEven.setEnabled(false);
        btnSalvarCatEven.setEnabled(true);
        btnExcluirCatEven.setEnabled(false);
        btnCancelarCatEven.setEnabled(true);
        btnPesquisarCatEven.setEnabled(false);

        
        preencherTabelaCategoriaEventos("SELECT * FROM CATEGORIA_EVENTOS ORDER BY COD_CATEVEN");
        
        
    }//GEN-LAST:event_btnNovoCatEvenActionPerformed

    private void btnExcluirCatEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCatEvenActionPerformed
         // BOTÃO EXCLUIR
        
        int resposta;
        
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir!");
        
        if ( resposta == JOptionPane.YES_OPTION ) {
           
            mcateven.setCod_cateven(Integer.parseInt(txtCodCatEven.getText()));
         
            controlCatEven.excluir(mcateven);
            
            // ABILITANDO/DESABILITANDO OS BOTÕES APÓS EXLUIR
            btnNovoCatEven.setEnabled(true);
            btnAlterarCatEven.setEnabled(!true);
            btnSalvarCatEven.setEnabled(false);
            btnExcluirCatEven.setEnabled(!true);
            btnCancelarCatEven.setEnabled(false);
            btnPesquisarCatEven.setEnabled(true);
            
            // LIMPANDO OS CAMPOS APÓS EXLCUIR
            txtCodCatEven.setText("");
            txtNomedaCategoriaEvento.setText("");
            txtCampoPesquisaCatEven.setText("");

            // ABILITANDO/DESABILITANDO OS CAMPOS APÓS EXCLUIR
            txtNomedaCategoriaEvento.setEnabled(false);
            txtCampoPesquisaCatEven.setEnabled(true);
            
            
            preencherTabelaCategoriaEventos("SELECT * FROM CATEGORIA_EVENTOS ORDER BY COD_CATEVEN");
            
      
        } else {
        
            // ABILITANDO/DESABILITANDO OS BOTÕES APÓS CLICAR EM "NÃO" EXLUIR
            btnNovoCatEven.setEnabled(true);
            btnAlterarCatEven.setEnabled(!true);
            btnSalvarCatEven.setEnabled(false);
            btnExcluirCatEven.setEnabled(!true);
            btnCancelarCatEven.setEnabled(false);
            btnPesquisarCatEven.setEnabled(true);

            // DESABILITANDO OS CAMPOS APÓS CLICAR EM "NÃO" EXCLUIR
            txtNomedaCategoriaEvento.setEnabled(false);
            txtCampoPesquisaCatEven.setEnabled(true);

            // LIMPANDO OS CAMPOS APÓS CLICAR EM "NÃO" EXLCUIR
            txtCodCatEven.setText("");
            txtNomedaCategoriaEvento.setText("");
            txtCampoPesquisaCatEven.setText("");
            
            
            preencherTabelaCategoriaEventos("SELECT * FROM CATEGORIA_EVENTOS ORDER BY COD_CATEVEN");
        
        }
            
        
         //preencherTabelaUsuario("select * from  usuarios where nome_usuario like '%" + musuario.getPesquisa() + "%'");
         
         
    }//GEN-LAST:event_btnExcluirCatEvenActionPerformed

    private void btnSalvarCatEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCatEvenActionPerformed
        // BOTÃO SALVAR

        // VALIDANDO OS CAMPOS ANTES DE SALVAR
        if (txtNomedaCategoriaEvento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Informe o nome da categoria!");
            txtNomedaCategoriaEvento.requestFocusInWindow();

        } else {

            if (flag == 1) {

                // SALVANDO OS DADOS NA BASE DE DADOS
                mcateven.setNome_cateven(txtNomedaCategoriaEvento.getText());
                

                controlCatEven.salvar(mcateven);
                

                // ABILITANDO/DESABILITANDO OS BOTÕES APÓS SALVAR
                btnNovoCatEven.setEnabled(true);
                btnAlterarCatEven.setEnabled(!true);
                btnSalvarCatEven.setEnabled(false);
                btnExcluirCatEven.setEnabled(!true);
                btnCancelarCatEven.setEnabled(false);
                btnPesquisarCatEven.setEnabled(true);

                // DESABILITANDO OS CAMPOS APÓS SALVAR
                txtNomedaCategoriaEvento.setEnabled(false);
                txtCampoPesquisaCatEven.setEnabled(true);

                // LIMPANDO OS CAMPOS APÓS SALVAR
                txtCodCatEven.setText("");
                txtNomedaCategoriaEvento.setText("");
                txtCampoPesquisaCatEven.setText("");

                preencherTabelaCategoriaEventos("SELECT * FROM CATEGORIA_EVENTOS ORDER BY COD_CATEVEN");

            } else {

                if (flag == 2) {

                    // DESABILITANDO O CAMPO PESQUISA
                    txtCampoPesquisaCatEven.setEnabled(false);
                    btnPesquisarCatEven.setEnabled(false);

                    mcateven.setCod_cateven(Integer.parseInt(txtCodCatEven.getText()));
                    mcateven.setNome_cateven(txtNomedaCategoriaEvento.getText());
                

                    controlCatEven.editar(mcateven);

                    // ABILITANDO/DESABILITANDO OS BOTÕES APÓS EDITAR
                    btnNovoCatEven.setEnabled(true);
                    btnAlterarCatEven.setEnabled(!true);
                    btnSalvarCatEven.setEnabled(false);
                    btnExcluirCatEven.setEnabled(!true);
                    btnCancelarCatEven.setEnabled(false);
                    btnPesquisarCatEven.setEnabled(true);

                    // ABILITANDO/DESABILITANDO OS CAMPOS APÓS EDITAR
                    txtNomedaCategoriaEvento.setEnabled(false);
                    txtCampoPesquisaCatEven.setEnabled(true);

                    // LIMPANDO OS CAMPOS APÓS EDITAR
                    txtCodCatEven.setText("");
                    txtNomedaCategoriaEvento.setText("");
                    txtCampoPesquisaCatEven.setText("");

                    preencherTabelaCategoriaEventos("SELECT * FROM CATEGORIA_EVENTOS ORDER BY COD_CATEVEN");
                }

            }

        }


         //preencherTabelaUsuario("select * from  usuarios where nome_usuario like '%" + musuario.getPesquisa() + "%'");
         
         
    }//GEN-LAST:event_btnSalvarCatEvenActionPerformed

    private void btnCancelarCatEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCatEvenActionPerformed
        // BOTÃO CANCELAR         

        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS CANCELAR
        btnNovoCatEven.setEnabled(true);
        btnAlterarCatEven.setEnabled(!true);
        btnSalvarCatEven.setEnabled(false);
        btnExcluirCatEven.setEnabled(!true);
        btnCancelarCatEven.setEnabled(false);
        btnPesquisarCatEven.setEnabled(true);

        // DESABILITANDO OS CAMPOS APÓS CANCELAR
        txtCodCatEven.setText("");
        txtNomedaCategoriaEvento.setEnabled(false);
        txtCampoPesquisaCatEven.setEnabled(true);

        // LIMPANDO OS CAMPOS APÓS CLICAR EM "NÃO" EXLCUIR
        txtCodCatEven.setText("");
        txtNomedaCategoriaEvento.setText("");
        txtCampoPesquisaCatEven.setText("");

        
        preencherTabelaCategoriaEventos("SELECT * FROM CATEGORIA_EVENTOS ORDER BY COD_CATEVEN");
        
        
    }//GEN-LAST:event_btnCancelarCatEvenActionPerformed

    private void jTableCategoriaEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCategoriaEventosMouseClicked
        // EVENTO NA TABELA QUE AO CLICAR SELECIONA O ITEM
        
        String nome_cateven = "" + jTableCategoriaEventos.getValueAt(jTableCategoriaEventos.getSelectedRow(), 1);

        // JOptionPane.showMessageDialog(rootPane, nome_cateven);
        
        // ABILITANDO/DESABILITANDO OS CAMPOS ANTES DE PESQUISAR
        btnNovoCatEven.setEnabled(true);
        btnAlterarCatEven.setEnabled(!true);
        btnExcluirCatEven.setEnabled(!true);
        btnCancelarCatEven.setEnabled(true);

        mcateven.setPesquisa(txtCampoPesquisaCatEven.getText());

        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS SELECIONAR ITEM NA TABELA
        btnNovoCatEven.setEnabled(true);
        btnAlterarCatEven.setEnabled(true);
        btnSalvarCatEven.setEnabled(false);
        btnExcluirCatEven.setEnabled(true);
        btnCancelarCatEven.setEnabled(!false);
        btnPesquisarCatEven.setEnabled(true);

        // DESABILITANDO OS CAMPOS APÓS SELECIONAR ITEM NA TABELA
        txtNomedaCategoriaEvento.setEnabled(false);
        txtCampoPesquisaCatEven.setEnabled(true);

        conectaCategoriaEventos.conexao();

        conectaCategoriaEventos.executaSQL("SELECT * FROM CATEGORIA_EVENTOS WHERE NOME_CATEVEN = '" + nome_cateven + "'");

        try {

            conectaCategoriaEventos.rs.first();

            txtCodCatEven.setText(String.valueOf(conectaCategoriaEventos.rs.getInt("COD_CATEVEN")));
            txtNomedaCategoriaEvento.setText(conectaCategoriaEventos.rs.getString("NOME_CATEVEN"));

            conectaCategoriaEventos.desconecta();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(rootPane, "Erro ao seleciona os dados! \n ERRO: " + ex);
            conectaCategoriaEventos.desconecta();
        }

        //conectaCategoriaEventos.desconecta();
        
       
    }//GEN-LAST:event_jTableCategoriaEventosMouseClicked

    
    
    public void preencherTabelaCategoriaEventos(String SQL) {
        
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[] {"Código da categoria","Nome da Categoria" };
        
        conectaCategoriaEventos.conexao();
        
        conectaCategoriaEventos.executaSQL(SQL);
        
        try {
            
            conectaCategoriaEventos.rs.first();
            
            do {
                
                dados.add(new Object[]{conectaCategoriaEventos.rs.getInt("COD_CATEVEN"), 
                    conectaCategoriaEventos.rs.getString("NOME_CATEVEN") });
            
               }while(conectaCategoriaEventos.rs.next());
            
        } catch (SQLException e) {

            // JOptionPane.showMessageDialog(rootPane, "Erro ao preencher a lista de categoria de eventos!");
            // JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList! \n ERRO" + e);

        }
        
        ModelTabela mtabelacategoriaeventos = new ModelTabela(dados, Colunas);
        
        jTableCategoriaEventos.setModel(mtabelacategoriaeventos);
        jTableCategoriaEventos.getColumnModel().getColumn(0).setPreferredWidth(132);
        jTableCategoriaEventos.getColumnModel().getColumn(0).setResizable(false);
        jTableCategoriaEventos.getColumnModel().getColumn(1).setPreferredWidth(140);
        jTableCategoriaEventos.getColumnModel().getColumn(1).setResizable(false);
        jTableCategoriaEventos.getTableHeader().setReorderingAllowed(false);
        jTableCategoriaEventos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableCategoriaEventos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        // conectaCategoriaEventos.desconecta();
        
      
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCategoriaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCategoriaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCategoriaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCategoriaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmCategoriaEventos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aaa;
    private javax.swing.JButton btnAlterarCatEven;
    private javax.swing.JButton btnCancelarCatEven;
    private javax.swing.JButton btnExcluirCatEven;
    private javax.swing.JButton btnNovoCatEven;
    private javax.swing.JButton btnPesquisarCatEven;
    private javax.swing.JButton btnSairCatEven;
    private javax.swing.JButton btnSalvarCatEven;
    private javax.swing.JLabel dddd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableCategoriaEventos;
    private javax.swing.JTextField txtCampoPesquisaCatEven;
    private javax.swing.JTextField txtCodCatEven;
    private javax.swing.JTextField txtNomedaCategoriaEvento;
    // End of variables declaration//GEN-END:variables
}
