package view;

import controller.ConexaoDB;
import controller.ControllerUsuarios;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import model.ModelTabela;
import model.ModelUsuarios;

/**
 *
 * @author Luis Carlos O.
 */
public class FrmUsuarios extends javax.swing.JFrame {
    
    ModelUsuarios musuario = new ModelUsuarios();
    ControllerUsuarios controlUsuario = new ControllerUsuarios();
    ConexaoDB conecta = new ConexaoDB();
    int flag = 0;

 
    public FrmUsuarios() {
        initComponents();

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/ss.jpg")).getImage());
        
        preencherTabelaUsuario("SELECT * FROM USUARIOS ORDER BY COD_USUARIO");
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAlterarUsuario = new javax.swing.JButton();
        btnNovoUsuario = new javax.swing.JButton();
        btnSalvarUsuario = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        btnCancelarUsuario = new javax.swing.JButton();
        btnSairUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        txtSobreNomeUsuario = new javax.swing.JTextField();
        txtNomeDeUsuario = new javax.swing.JTextField();
        txtPasswordUsuario = new javax.swing.JPasswordField();
        txtConfPasswordUsuario = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        txtCampoPesquisaUsuario = new javax.swing.JTextField();
        btnPesquisarUsuario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCodUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuários");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Opções", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        btnAlterarUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-suporte-50.png"))); // NOI18N
        btnAlterarUsuario.setToolTipText("Alterar");
        btnAlterarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarUsuario.setEnabled(false);
        btnAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarUsuarioActionPerformed(evt);
            }
        });

        btnNovoUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-50.png"))); // NOI18N
        btnNovoUsuario.setToolTipText("Adicionar");
        btnNovoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoUsuarioActionPerformed(evt);
            }
        });

        btnSalvarUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-salvar-50.png"))); // NOI18N
        btnSalvarUsuario.setToolTipText("Salvar");
        btnSalvarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvarUsuario.setEnabled(false);
        btnSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUsuarioActionPerformed(evt);
            }
        });

        btnExcluirUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-lixo-50.png"))); // NOI18N
        btnExcluirUsuario.setToolTipText("Excluir");
        btnExcluirUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirUsuario.setEnabled(false);
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });

        btnCancelarUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancelar-50.png"))); // NOI18N
        btnCancelarUsuario.setToolTipText("Cancelar");
        btnCancelarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarUsuario.setEnabled(false);
        btnCancelarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarUsuarioActionPerformed(evt);
            }
        });

        btnSairUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSairUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sair-50.png"))); // NOI18N
        btnSairUsuario.setToolTipText("Sair");
        btnSairUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSairUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnSalvarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnSairUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSairUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("Nome*:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("Sobrenome*:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("Nome de usuário*:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("Senha*:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Conf. Senha*:");

        txtNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeUsuario.setEnabled(false);

        txtSobreNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSobreNomeUsuario.setEnabled(false);

        txtNomeDeUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeDeUsuario.setEnabled(false);

        txtPasswordUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPasswordUsuario.setEnabled(false);
        txtPasswordUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordUsuarioActionPerformed(evt);
            }
        });

        txtConfPasswordUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtConfPasswordUsuario.setEnabled(false);
        txtConfPasswordUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfPasswordUsuarioActionPerformed(evt);
            }
        });

        jTableUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableUsuario.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuario);

        txtCampoPesquisaUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnPesquisarUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesquisarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-25.png"))); // NOI18N
        btnPesquisarUsuario.setToolTipText("Pesquisar");
        btnPesquisarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarUsuarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Cod:");

        txtCodUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCodUsuario.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSobreNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfPasswordUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(txtCampoPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSobreNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtConfPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txtCampoPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );

        setBounds(730, 270, 656, 448);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioActionPerformed
        // BOTÃO ALTERAR
        
        flag = 2;
        
        // ABILITANDO/DESABILITANDO OS CAMPOS
        txtNomeUsuario.setEnabled(true);
        txtSobreNomeUsuario.setEnabled(true);
        txtNomeDeUsuario.setEnabled(true);
        txtPasswordUsuario.setEnabled(true);
        txtConfPasswordUsuario.setEnabled(true);
        txtCampoPesquisaUsuario.setEnabled(false);
        
        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS CLICAR NO BOTÃO
        btnNovoUsuario.setEnabled(false);
        btnAlterarUsuario.setEnabled(false);
        btnSalvarUsuario.setEnabled(true);
        btnExcluirUsuario.setEnabled(false);
        btnCancelarUsuario.setEnabled(true);
        btnPesquisarUsuario.setEnabled(false);
        
        preencherTabelaUsuario("SELECT * FROM USUARIOS ORDER BY COD_USUARIO");
        
        
    }//GEN-LAST:event_btnAlterarUsuarioActionPerformed

    private void btnNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoUsuarioActionPerformed
        // BOTÃO NOVO
        
        flag = 1;
        
        // LIMPANDO OS CAMPOS APÓS CLICAR
        txtCodUsuario.setText("");
        txtNomeUsuario.setText("");
        txtSobreNomeUsuario.setText("");
        txtNomeDeUsuario.setText("");
        txtPasswordUsuario.setText("");
        txtConfPasswordUsuario.setText("");
        txtCampoPesquisaUsuario.setText("");
        
        // ABILITANDO OS CAMPOS
        txtNomeUsuario.setEnabled(true);
        txtSobreNomeUsuario.setEnabled(true);
        txtNomeDeUsuario.setEnabled(true);
        txtPasswordUsuario.setEnabled(true);
        txtConfPasswordUsuario.setEnabled(true);
        txtCampoPesquisaUsuario.setEnabled(false);
        
        // COLOCANDO FOCO NOS CAMPOS
        txtNomeUsuario.requestFocusInWindow();
        
        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS CLICAR NO BOTÃO
        btnNovoUsuario.setEnabled(false);
        btnAlterarUsuario.setEnabled(false);
        btnSalvarUsuario.setEnabled(true);
        btnExcluirUsuario.setEnabled(false);
        btnCancelarUsuario.setEnabled(true);
        btnPesquisarUsuario.setEnabled(false);
        
        
        preencherTabelaUsuario("SELECT * FROM USUARIOS ORDER BY COD_USUARIO");
        
        
    }//GEN-LAST:event_btnNovoUsuarioActionPerformed

    private void btnSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUsuarioActionPerformed
        // BOTÃO SALVAR

        // VALIDANDO OS CAMPOS ANTES DE SALVAR
        if ( txtNomeUsuario.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(rootPane, "Favor informe o nome!");
            txtNomeUsuario.requestFocusInWindow();
            return;
        }
        
        if ( txtSobreNomeUsuario.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(rootPane, "Favor informe o sobrenome!");
            txtSobreNomeUsuario.requestFocusInWindow();
            return;
        }
        
        if ( txtNomeDeUsuario.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(rootPane, "Favor informe o nome de usuário!");
            txtNomeDeUsuario.requestFocusInWindow();
            return;
        }
        
        if ( txtPasswordUsuario.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(rootPane, "Favor informe a senha!");
            txtPasswordUsuario.requestFocusInWindow();
            return;
        }
        
        if ( txtConfPasswordUsuario.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(rootPane, "Favor confirme a senha!");
            txtConfPasswordUsuario.requestFocusInWindow();
            return;
        }
        
        if ( txtPasswordUsuario.getText() == null ? txtConfPasswordUsuario.getText() != null : !txtPasswordUsuario.getText().equals(txtConfPasswordUsuario.getText()) ) {
            JOptionPane.showMessageDialog(rootPane, "Favor confirmar a senha para concluir!");
            txtPasswordUsuario.setText("");
            txtConfPasswordUsuario.setText("");
            txtPasswordUsuario.requestFocusInWindow();
        } else {
        
        if ( flag == 1 ) {
        
        // SALVANDO OS DADOS NA BASE DE DADOS
        musuario.setNome_usuario(txtNomeUsuario.getText());
        musuario.setSobrenome_usuario(txtSobreNomeUsuario.getText());
        musuario.setNome_de_usuario(txtNomeDeUsuario.getText());
        musuario.setSenha_usuario(txtPasswordUsuario.getText());
   

        controlUsuario.salvar(musuario);
        
        
        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS SALVAR
        btnNovoUsuario.setEnabled(true);
        btnAlterarUsuario.setEnabled(!true);
        btnSalvarUsuario.setEnabled(false);
        btnExcluirUsuario.setEnabled(!true);
        btnCancelarUsuario.setEnabled(false);
        btnPesquisarUsuario.setEnabled(true);
        
        // DESABILITANDO OS CAMPOS APÓS SALVAR
        txtNomeUsuario.setEnabled(false);
        txtSobreNomeUsuario.setEnabled(false);
        txtNomeDeUsuario.setEnabled(false);
        txtPasswordUsuario.setEnabled(false);
        txtConfPasswordUsuario.setEnabled(false);
        txtCampoPesquisaUsuario.setEnabled(true);
        
        // LIMPANDO OS CAMPOS APÓS SALVAR
        txtCodUsuario.setText("");
        txtNomeUsuario.setText("");
        txtSobreNomeUsuario.setText("");
        txtNomeDeUsuario.setText("");
        txtPasswordUsuario.setText("");
        txtConfPasswordUsuario.setText("");
        txtCampoPesquisaUsuario.setText("");
        
        
        preencherTabelaUsuario("SELECT * FROM USUARIOS ORDER BY COD_USUARIO");
        
        
        } else {
            
            if  ( flag == 2 ) {
                
                    // DESABILITANDO O CAMPO PESQUISA
                    txtCampoPesquisaUsuario.setEnabled(false);
                    btnPesquisarUsuario.setEnabled(false);
                    
                    musuario.setCod_usuario(Integer.parseInt(txtCodUsuario.getText()));
                    musuario.setNome_usuario(txtNomeUsuario.getText());
                    musuario.setSobrenome_usuario(txtSobreNomeUsuario.getText());
                    musuario.setNome_de_usuario(txtNomeDeUsuario.getText());
                    musuario.setSenha_usuario(txtPasswordUsuario.getText());
                   
                    
                    controlUsuario.editar(musuario);
                    
                    
                    // ABILITANDO/DESABILITANDO OS BOTÕES APÓS EDITAR
                    btnNovoUsuario.setEnabled(true);
                    btnAlterarUsuario.setEnabled(!true);
                    btnSalvarUsuario.setEnabled(false);
                    btnExcluirUsuario.setEnabled(!true);
                    btnCancelarUsuario.setEnabled(false);
                    btnPesquisarUsuario.setEnabled(true);
                    
                    // ABILITANDO/DESABILITANDO OS CAMPOS APÓS EDITAR
                    txtNomeUsuario.setEnabled(false);
                    txtSobreNomeUsuario.setEnabled(false);
                    txtNomeDeUsuario.setEnabled(false);
                    txtPasswordUsuario.setEnabled(false);
                    txtConfPasswordUsuario.setEnabled(false);
                    txtCampoPesquisaUsuario.setEnabled(true);
                    
                    // LIMPANDO OS CAMPOS APÓS EDITAR
                    txtCodUsuario.setText("");
                    txtNomeUsuario.setText("");
                    txtSobreNomeUsuario.setText("");
                    txtNomeDeUsuario.setText("");
                    txtPasswordUsuario.setText("");
                    txtConfPasswordUsuario.setText("");
                    txtCampoPesquisaUsuario.setText("");
                    
 
                    preencherTabelaUsuario("SELECT * FROM USUARIOS ORDER BY COD_USUARIO");

                }

            }

        }
        

         //preencherTabelaUsuario("select * from  usuarios where nome_usuario like '%" + musuario.getPesquisa() + "%'");
         
         
    }//GEN-LAST:event_btnSalvarUsuarioActionPerformed

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
        // BOTÃO EXCLUIR
        
        int resposta;
        
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir!");
        
        if ( resposta == JOptionPane.YES_OPTION ) {
           
            musuario.setCod_usuario(Integer.parseInt(txtCodUsuario.getText()));
         
            controlUsuario.excluir(musuario);
            
            // ABILITANDO/DESABILITANDO OS BOTÕES APÓS EXLUIR
            btnNovoUsuario.setEnabled(true);
            btnAlterarUsuario.setEnabled(!true);
            btnSalvarUsuario.setEnabled(false);
            btnExcluirUsuario.setEnabled(!true);
            btnCancelarUsuario.setEnabled(false);
            btnPesquisarUsuario.setEnabled(true);
            
            // LIMPANDO OS CAMPOS APÓS EXLCUIR
            txtCodUsuario.setText("");
            txtNomeUsuario.setText("");
            txtSobreNomeUsuario.setText("");
            txtNomeDeUsuario.setText("");
            txtPasswordUsuario.setText("");
            txtConfPasswordUsuario.setText("");
            txtCampoPesquisaUsuario.setText("");

            // ABILITANDO/DESABILITANDO OS CAMPOS APÓS EXCLUIR
            txtNomeUsuario.setEnabled(false);
            txtSobreNomeUsuario.setEnabled(false);
            txtNomeDeUsuario.setEnabled(false);
            txtPasswordUsuario.setEnabled(false);
            txtConfPasswordUsuario.setEnabled(false);
            txtCampoPesquisaUsuario.setEnabled(true);
            
            
            preencherTabelaUsuario("SELECT * FROM USUARIOS ORDER BY COD_USUARIO");
            
      
        } else {
        
            // ABILITANDO/DESABILITANDO OS BOTÕES APÓS CLICAR EM "NÃO" EXLUIR
            btnNovoUsuario.setEnabled(true);
            btnAlterarUsuario.setEnabled(!true);
            btnSalvarUsuario.setEnabled(false);
            btnExcluirUsuario.setEnabled(!true);
            btnCancelarUsuario.setEnabled(false);
            btnPesquisarUsuario.setEnabled(true);

            // DESABILITANDO OS CAMPOS APÓS CLICAR EM "NÃO" EXCLUIR
            txtNomeUsuario.setEnabled(false);
            txtSobreNomeUsuario.setEnabled(false);
            txtNomeDeUsuario.setEnabled(false);
            txtPasswordUsuario.setEnabled(false);
            txtConfPasswordUsuario.setEnabled(false);
            txtCampoPesquisaUsuario.setEnabled(true);

            // LIMPANDO OS CAMPOS APÓS CLICAR EM "NÃO" EXLCUIR
            txtCodUsuario.setText("");
            txtNomeUsuario.setText("");
            txtSobreNomeUsuario.setText("");
            txtNomeDeUsuario.setText("");
            txtPasswordUsuario.setText("");
            txtConfPasswordUsuario.setText("");
            txtCampoPesquisaUsuario.setText("");
            
            
            preencherTabelaUsuario("SELECT * FROM USUARIOS ORDER BY COD_USUARIO");
        
        }
            
        
         preencherTabelaUsuario("select * from  usuarios where nome_usuario like '%" + musuario.getPesquisa() + "%'");
        
 
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void btnCancelarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarUsuarioActionPerformed
        
        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS CANCELAR
        btnNovoUsuario.setEnabled(true);
        btnAlterarUsuario.setEnabled(!true);
        btnSalvarUsuario.setEnabled(false);
        btnExcluirUsuario.setEnabled(!true);
        btnCancelarUsuario.setEnabled(false);
        btnPesquisarUsuario.setEnabled(true);
        
        // DESABILITANDO OS CAMPOS APÓS CANCELAR
        txtCodUsuario.setText("");
        txtNomeUsuario.setEnabled(false);
        txtSobreNomeUsuario.setEnabled(false);
        txtNomeDeUsuario.setEnabled(false);
        txtPasswordUsuario.setEnabled(false);
        txtConfPasswordUsuario.setEnabled(false);
        txtCampoPesquisaUsuario.setEnabled(true);
        
        // LIMPANDO OS CAMPOS APÓS CLICAR EM "NÃO" EXLCUIR
        txtCodUsuario.setText("");
        txtNomeUsuario.setText("");
        txtSobreNomeUsuario.setText("");
        txtNomeDeUsuario.setText("");
        txtPasswordUsuario.setText("");
        txtConfPasswordUsuario.setText("");
        txtCampoPesquisaUsuario.setText("");
        
        
        preencherTabelaUsuario("SELECT * FROM USUARIOS ORDER BY COD_USUARIO");
            
        
    }//GEN-LAST:event_btnCancelarUsuarioActionPerformed

    private void btnPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarUsuarioActionPerformed
        // BOTÃO PESQUISAR
        
        if ( txtCampoPesquisaUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Favor informe o nome para pesquisar!");
            txtCampoPesquisaUsuario.requestFocusInWindow();
            
        } else if ( !txtCampoPesquisaUsuario.getText().isEmpty() ) {
           
        // ABILITANDO/DESABILITANDO OS BOTÕES ANTES DE PESQUISAR
        btnNovoUsuario.setEnabled(true);
        btnAlterarUsuario.setEnabled(!true);
        btnExcluirUsuario.setEnabled(!true);
        btnCancelarUsuario.setEnabled(true);
        
        
        musuario.setPesquisa(txtCampoPesquisaUsuario.getText());
        
        ModelUsuarios modelUsuario = controlUsuario.buscarUsuario(musuario);
        
        /*
        
        txtCodUsuario.setText(String.valueOf(modelUsuario.getCod_usuario()));
        txtNomeUsuario.setText(modelUsuario.getNome_usuario());
        txtSobreNomeUsuario.setText(modelUsuario.getSobrenome_usuario());
        txtNomeDeUsuario.setText(modelUsuario.getNome_de_usuario());
        txtPasswordUsuario.setText(modelUsuario.getSenha_usuario());
        
        */
        
        preencherTabelaUsuario("select * from usuarios where nome_usuario like '%" + musuario.getPesquisa() + "%'");
        
        txtCampoPesquisaUsuario.setText("");
        
        
        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS PESQUISAR
        btnNovoUsuario.setEnabled(true);
        btnAlterarUsuario.setEnabled(!true);
        btnSalvarUsuario.setEnabled(false);
        btnExcluirUsuario.setEnabled(!true);
        btnCancelarUsuario.setEnabled(!false);
        btnPesquisarUsuario.setEnabled(true);
        
        // DESABILITANDO OS CAMPOS APÓS PESQUISAR
        txtNomeUsuario.setEnabled(false);
        txtSobreNomeUsuario.setEnabled(false);
        txtNomeDeUsuario.setEnabled(false);
        txtPasswordUsuario.setEnabled(false);
        txtConfPasswordUsuario.setEnabled(false);
        
        // LIMPANDO OS CAMOPS APÓS PESQUISAR
        txtCodUsuario.setText("");
        txtNomeUsuario.setText("");
        txtSobreNomeUsuario.setText("");
        txtNomeDeUsuario.setText("");
        txtPasswordUsuario.setText("");
        txtConfPasswordUsuario.setText("");
        
        
       // preencherTabelaUsuario("SELECT * FROM USUARIOS ORDER BY COD_USUARIO");
        
        } else if ( musuario.getPesquisa().equals("")) {
            
            preencherTabelaUsuario("SELECT * FROM USUARIOS ORDER BY COD_USUARIO");
        }
        
        //preencherTabelaUsuario("select * from  usuarios where nome_usuario like '%" + musuario.getPesquisa() + "%'");
        
        
    }//GEN-LAST:event_btnPesquisarUsuarioActionPerformed

    private void btnSairUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairUsuarioActionPerformed
        // BOTÃO SAIR
        
        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS SAIR
        btnNovoUsuario.setEnabled(true);
        btnAlterarUsuario.setEnabled(!true);
        btnSalvarUsuario.setEnabled(false);
        btnExcluirUsuario.setEnabled(!true);
        btnCancelarUsuario.setEnabled(false);
        btnPesquisarUsuario.setEnabled(true);
        
        // DESABILITANDO OS CAMPOS APÓS SAIR
        txtCodUsuario.setText("");
        txtNomeUsuario.setEnabled(false);
        txtSobreNomeUsuario.setEnabled(false);
        txtNomeDeUsuario.setEnabled(false);
        txtPasswordUsuario.setEnabled(false);
        txtConfPasswordUsuario.setEnabled(false);
        txtCampoPesquisaUsuario.setEnabled(true);
        
        // LIMPANDO OS CAMPOS APÓS CLICAR EM SAIR
        txtCodUsuario.setText("");
        txtNomeUsuario.setText("");
        txtSobreNomeUsuario.setText("");
        txtNomeDeUsuario.setText("");
        txtPasswordUsuario.setText("");
        txtConfPasswordUsuario.setText("");
        txtCampoPesquisaUsuario.setText("");
        
        
        dispose();
        
        preencherTabelaUsuario("SELECT * FROM USUARIOS ORDER BY COD_USUARIO");
        
        
    }//GEN-LAST:event_btnSairUsuarioActionPerformed

    private void txtPasswordUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordUsuarioActionPerformed

    private void txtConfPasswordUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfPasswordUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfPasswordUsuarioActionPerformed

    private void jTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMouseClicked
        // EVENTO NA TABELA QUE AO CLICAR SELECIONA O ITEM
        
        String nome_usuario = "" + jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 1);
        
       // JOptionPane.showMessageDialog(rootPane, nome_usuario);
       
       
       // ABILITANDO/DESABILITANDO OS CAMPOS ANTES DE PESQUISAR
        btnNovoUsuario.setEnabled(true);
        btnAlterarUsuario.setEnabled(!true);
        btnExcluirUsuario.setEnabled(!true);
        btnCancelarUsuario.setEnabled(true);
        
        musuario.setPesquisa(txtCampoPesquisaUsuario.getText());
        
        // ABILITANDO/DESABILITANDO OS BOTÕES APÓS SELECIONAR ITEM NA TABELA
        btnNovoUsuario.setEnabled(true);
        btnAlterarUsuario.setEnabled(true);
        btnSalvarUsuario.setEnabled(false);
        btnExcluirUsuario.setEnabled(true);
        btnCancelarUsuario.setEnabled(!false);
        btnPesquisarUsuario.setEnabled(true);
        
        // DESABILITANDO OS CAMPOS APÓS SELECIONAR ITEM NA TABELA
        txtNomeUsuario.setEnabled(false);
        txtSobreNomeUsuario.setEnabled(false);
        txtNomeDeUsuario.setEnabled(false);
        txtPasswordUsuario.setEnabled(false);
        txtConfPasswordUsuario.setEnabled(false);
        txtCampoPesquisaUsuario.setEnabled(true);
       
       
        conecta.conexao();
        
        conecta.executaSQL("SELECT * FROM USUARIOS WHERE NOME_USUARIO = '"+nome_usuario+"'");
        
        try {
            
            conecta.rs.first();
            
            txtCodUsuario.setText(String.valueOf(conecta.rs.getInt("cod_usuario")));
            txtNomeUsuario.setText(conecta.rs.getString("nome_usuario"));
            txtSobreNomeUsuario.setText(conecta.rs.getString("sobrenome_usuario"));
            txtNomeDeUsuario.setText(conecta.rs.getString("nome_de_usuario"));
            txtPasswordUsuario.setText(conecta.rs.getString("senha_usuario"));
            
            conecta.desconecta();
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro ao seleciona os dados! \n ERRO: " + ex);
        }
        
       // conecta.desconecta();
        
        
    }//GEN-LAST:event_jTableUsuarioMouseClicked

  
    
    public void preencherTabelaUsuario(String SQL) {
        
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[] {"Cod","Nome","Sobrenome","Usuário" };
        
        conecta.conexao();
        
        conecta.executaSQL(SQL);
        
        try {
            
            conecta.rs.first();
            
            do {
                
                dados.add(new Object[]{conecta.rs.getInt("cod_usuario"), 
                    conecta.rs.getString("nome_usuario"), 
                    conecta.rs.getString("sobrenome_usuario"), 
                    conecta.rs.getString("nome_de_usuario")});
            
               }while(conecta.rs.next());
            
        } catch (SQLException e) {

            // JOptionPane.showMessageDialog(rootPane, "Erro ao preencher lista de usuários!");
            // JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList! \n ERRO" + e);

        }
        
        ModelTabela mtabelausuario = new ModelTabela(dados, Colunas);
        
        jTableUsuario.setModel(mtabelausuario);
        jTableUsuario.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableUsuario.getColumnModel().getColumn(0).setResizable(false);
        jTableUsuario.getColumnModel().getColumn(1).setPreferredWidth(125);
        jTableUsuario.getColumnModel().getColumn(1).setResizable(false);
        jTableUsuario.getColumnModel().getColumn(2).setPreferredWidth(125);
        jTableUsuario.getColumnModel().getColumn(2).setResizable(false);
        jTableUsuario.getColumnModel().getColumn(3).setPreferredWidth(125);
        jTableUsuario.getColumnModel().getColumn(3).setResizable(false);
        jTableUsuario.getTableHeader().setReorderingAllowed(false);
        jTableUsuario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        // conecta.desconecta();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmUsuarios().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarUsuario;
    private javax.swing.JButton btnCancelarUsuario;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JButton btnNovoUsuario;
    private javax.swing.JButton btnPesquisarUsuario;
    private javax.swing.JButton btnSairUsuario;
    private javax.swing.JButton btnSalvarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField txtCampoPesquisaUsuario;
    private javax.swing.JTextField txtCodUsuario;
    private javax.swing.JPasswordField txtConfPasswordUsuario;
    private javax.swing.JTextField txtNomeDeUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JPasswordField txtPasswordUsuario;
    private javax.swing.JTextField txtSobreNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
