package view;

import controller.ConexaoDB;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * @author Luis Carlos O.
 */
public class TelaLogin extends javax.swing.JFrame {
    
    ConexaoDB conectalogin = new ConexaoDB();
    

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/ss.jpg")).getImage());
        
        
        //conectalogin.conexao();
        
        
        preencherComboUsuario();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        mensagenBemVindo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        txtPasswordLogin = new javax.swing.JPasswordField();
        btnLogar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxUsuario = new javax.swing.JComboBox<>();
        fundoLogin = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(null);

        mensagenBemVindo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        mensagenBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensagenBemVindo.setText("Bem Vindo");
        getContentPane().add(mensagenBemVindo);
        mensagenBemVindo.setBounds(410, 30, 150, 50);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabelUsuario.setText("Usuário:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(350, 110, 50, 30);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(360, 150, 50, 30);

        txtPasswordLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPasswordLogin.setToolTipText("Sua senha");
        txtPasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtPasswordLogin);
        txtPasswordLogin.setBounds(410, 150, 150, 30);

        btnLogar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-selecionado-25.png"))); // NOI18N
        btnLogar.setText("OK");
        btnLogar.setToolTipText("Logar");
        btnLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogar);
        btnLogar.setBounds(410, 200, 70, 40);

        btnSair.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancelar-25.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("Sair");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(490, 200, 70, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/snake.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 270, 180, 50);

        jLabel2.setText("Copyright - Todos os direitos reservados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 320, 230, 20);

        jLabel3.setText("kb.luiscarlos@live.com  (71)9 8412-3574");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 340, 230, 20);

        jComboBoxUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erro Conexao" }));
        jComboBoxUsuario.setToolTipText("selecione seu nome de usuário");
        jComboBoxUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBoxUsuario);
        jComboBoxUsuario.setBounds(410, 110, 150, 30);

        fundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoLogin.jpg"))); // NOI18N
        getContentPane().add(fundoLogin);
        fundoLogin.setBounds(0, 0, 590, 370);

        setSize(new java.awt.Dimension(603, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed


     //   if (txtUsuarioLogin.getText().equals("Luis") && txtPasswordLogin.getText().equals("123") ) {

            // CHAMAR TELA PRINCIPAL
      //      TelaHome telaprincial = new TelaHome();

       //     telaprincial.setVisible(true);
       //     dispose(); // Apos chamar a tela principal a tela de login fecha

     //   } else {
     
            
     
            try {

                conectalogin.conexao();
                
                if ( txtPasswordLogin.getText().isEmpty() ) {

                    txtPasswordLogin.setText("");
                    txtPasswordLogin.requestFocusInWindow();
                    JOptionPane.showMessageDialog(rootPane, "Campo senha vazio!");

                } else {

                    String sqlLogin = ("SELECT * FROM USUARIOS WHERE NOME_DE_USUARIO = '" + jComboBoxUsuario.getSelectedItem() + "'");

                    conectalogin.executaSQL(sqlLogin);

                    conectalogin.rs.first();

                    if ( conectalogin.rs.getString("SENHA_USUARIO").equals(txtPasswordLogin.getText()) ) {

                        // CHAMAR TELA PRINCIPAL
                        TelaHome telaprincipal = new TelaHome(jComboBoxUsuario.getSelectedItem().toString());

                        telaprincipal.setVisible(true);
                        dispose(); // Apos chamar a tela principal a tela de login fecha

                    } else {

                        txtPasswordLogin.setText("");
                        txtPasswordLogin.requestFocusInWindow();
                        JOptionPane.showMessageDialog(rootPane, "Senha Inválida");

                    }

                }
                
                conectalogin.desconecta();

            } catch (SQLException ex) {

                //JOptionPane.showMessageDialog(rootPane, "Usuário ou senha inválidos");
            }

      //  }
      
        

    }//GEN-LAST:event_btnLogarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        // BOTAO SAIR
        //this.dispose();
        //dispose();
        System.exit(0b0);
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtPasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordLoginActionPerformed

    
    
    public void preencherComboUsuario() {

        conectalogin.conexao();

        conectalogin.executaSQL("SELECT * FROM USUARIOS ORDER BY NOME_DE_USUARIO");

        // REMOVE TODOS OS ITENS DA COMOBOX QUE VEM POR PADRAO PARA PODER ARMAZENAR OS ITENS QUE VEM DA BASE DE DADOS
        jComboBoxUsuario.removeAllItems();

        try {

            conectalogin.rs.first();

            do {

                jComboBoxUsuario.addItem(conectalogin.rs.getString("NOME_DE_USUARIO"));

            } while (conectalogin.rs.next());

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(rootPane, "Erro ao conectar com a base de dados!! Login.. ");
            // JOptionPane.showMessageDialog(rootPane, "Erro ao preencher usuarios \n ERROR: " + ex);

        }

        conectalogin.desconecta();

    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel fundoLogin;
    private javax.swing.JComboBox<String> jComboBoxUsuario;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel mensagenBemVindo;
    private javax.swing.JPasswordField txtPasswordLogin;
    // End of variables declaration//GEN-END:variables

}
