package view;

import controller.ConexaoDB;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Luis Carlos O.
 */
public class TelaHome extends javax.swing.JFrame {

    // FAZ COM QUE O MESMO JFRAME ABRA UMA VEZ
    // SEM A NECESSIDADE DE INSTACIAR LA EMBAIXO
    FrmUsuarios frmUsuarios;
    FrmEventos frmAgendamentos;
    FrmProdutos frmProdutos;
    FrmRelatorios frmRelatorios;
    TelaSobre telaSobre;
    TelaLoadEnd telaLoadEnd;
    

    ConexaoDB conecta = new ConexaoDB();
    FrmRelatorios preencheComboDoEventoNoGerarReport = new FrmRelatorios();
    
    
    /**
     * Creates new form TelaHome
     * @param usuario
     */
    public TelaHome(String usuario) {
        initComponents();
        
        
        txtUsuarioLogado.setText(usuario);
        

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/ss.jpg")).getImage());
        
        
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        
        // PONDO MENSAGEM DE BOAS VINDAS EM MOVIMENTO
        new Thread() {
            
            @Override
            public void run() {
                
                int x = 1080;
                int y = txtBoasVindas.getLocation().y;
                
                do {
                    
                    x--;
                    
                    if ( x < -100 ) {
                        
                        x = 1080;
                        
                    }
                    
                    txtBoasVindas.setLocation(x, y);
                    
                    
                    try {
                        
                        sleep(10);
                        
                    } catch (InterruptedException e) {
                        
                        //
                        
                    }
                    
                    
                }while(true);
                
            }
            
            
        } .start();
        
                
        
        Calendar data = Calendar.getInstance();
        
        Date d = data.getTime();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        dateFormat.format(d);
        
        String dtHoje;
        dtHoje = dateFormat.format(d);
        
        
        
        
        //JOptionPane.showMessageDialog(rootPane, "Bem Vindo");
        
        // TANTO AQUI COMO FORA A CONEXAO REALIZA COM SUCESSO
        // ConexaoDB conecta = new ConexaoDB();
        conecta.conexao();
        //System.out.println(conecta);
     

    }

    private TelaHome() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnAgendamento = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnSobre = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDataHome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHoraHome = new javax.swing.JLabel();
        txtUsuarioLogado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBoasVindas = new javax.swing.JLabel();
        fundoHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página Inicial");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Menu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-usuário-50.png"))); // NOI18N
        btnUsuario.setText("            Usuários");
        btnUsuario.setToolTipText("Cadastrar, Alterar, Deletar e Buscar Usuário");
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuario);

        btnAgendamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-calendário-50.png"))); // NOI18N
        btnAgendamento.setText("  Agendamentos");
        btnAgendamento.setToolTipText("Cadastrar, Alterar, Deletar e Buscar Evento");
        btnAgendamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendamentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgendamento);

        btnProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-lista-com-marcadores.png"))); // NOI18N
        btnProduto.setText("           Produtos");
        btnProduto.setToolTipText("Cadastrar, Alterar, Deletar e Buscar Produto");
        btnProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnProduto);

        btnRelatorio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-treinamento-50.png"))); // NOI18N
        btnRelatorio.setText("         Relátorios");
        btnRelatorio.setToolTipText("Gerar Relátorios");
        btnRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        jPanel1.add(btnRelatorio);

        btnSobre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sobre-50.png"))); // NOI18N
        btnSobre.setText("              Sobre");
        btnSobre.setToolTipText("Sobre");
        btnSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSobre.setMaximumSize(new java.awt.Dimension(185, 59));
        btnSobre.setMinimumSize(new java.awt.Dimension(185, 59));
        btnSobre.setPreferredSize(new java.awt.Dimension(185, 59));
        btnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreActionPerformed(evt);
            }
        });
        jPanel1.add(btnSobre);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sair-50.png"))); // NOI18N
        btnSair.setText("                   Sair");
        btnSair.setToolTipText("Sair do Sistema");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 210, 460);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Data:");
        jPanel2.add(jLabel1);

        txtDataHome.setBackground(new java.awt.Color(255, 255, 255));
        txtDataHome.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtDataHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDataHome.setText("Data");
        jPanel2.add(txtDataHome);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Hora:");
        jPanel2.add(jLabel2);

        txtHoraHome.setBackground(new java.awt.Color(255, 255, 255));
        txtHoraHome.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtHoraHome.setText("Hora");
        txtHoraHome.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtHoraHome);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(230, 570, 830, 50);

        txtUsuarioLogado.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(txtUsuarioLogado);
        txtUsuarioLogado.setBounds(100, 580, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Usuário:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 580, 60, 30);

        txtBoasVindas.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txtBoasVindas.setForeground(new java.awt.Color(255, 255, 255));
        txtBoasVindas.setText("Bem Vindo!");
        getContentPane().add(txtBoasVindas);
        txtBoasVindas.setBounds(480, 20, 120, 20);

        fundoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoHome.jpg"))); // NOI18N
        getContentPane().add(fundoHome);
        fundoHome.setBounds(0, -10, 1730, 680);

        setSize(new java.awt.Dimension(1080, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // BOTÃO USUÁRIO
        
        if ( frmUsuarios == null ) {
            
            
            frmUsuarios = new FrmUsuarios();
            
        }
        
        frmUsuarios.setVisible(true);
        

    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendamentoActionPerformed
        // BOTÃO AGENDAMENTOS
    
        if (frmAgendamentos == null) {

            frmAgendamentos = new FrmEventos();

        }

        frmAgendamentos.setVisible(true);
        
        
    }//GEN-LAST:event_btnAgendamentoActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        // BOTÃO PRODUTO
       
        if (frmProdutos == null) {

            frmProdutos = new FrmProdutos();

        } 

        frmProdutos.setVisible(true);
        
        
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // BOTÃO RELÁTORIO
        
        
        /*
         ANTES DE ABRIR O FORMULARIO DE GERAR RELATORIO CARREGA A COMOBOBOX
         DO EVENTO, ISSO FAZ COM QUE CASO TENHA ALGUMA ALTERAÇÃO EM ALGUM EVENTOS
         TIPO: ADICIONAR, EXCLUIR ... CARREGA NA COMOBO. SEM ISSO NÃO CARREGA
         AS ALTERAÇÕES.
         */
        
        
        preencheComboDoEventoNoGerarReport.preencherComboNomeEvento();
        
        
         if (frmRelatorios == null) {
             
             
            preencheComboDoEventoNoGerarReport.preencherComboNomeEvento();

            frmRelatorios = new FrmRelatorios();

        } 

        
        preencheComboDoEventoNoGerarReport.preencherComboNomeEvento();
         
        frmRelatorios.setVisible(true);
        
        
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // BOTÃO DE SAIR
        
        // conecta.desconecta();
        
        /*
        if ( telaLoadEnd == null ) {
            
            telaLoadEnd = new TelaLoadEnd();
            
        }
        
        telaLoadEnd.setVisible(true);
        */
        
        int optionn = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Atenção", JOptionPane.YES_OPTION);

        if (optionn == JOptionPane.YES_OPTION) {

            conecta.desconecta();

            if (telaLoadEnd == null) {

                telaLoadEnd = new TelaLoadEnd();

            }

            telaLoadEnd.setVisible(true);

        }


        // System.exit(0b0);
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        txtDataHome.setText(formato.format(dataSistema));
        
        
        Timer timer = new Timer(1000, new hora());
        timer.start();
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreActionPerformed
        // BOTÂO SOBRE
        
        if (telaSobre == null) {

            telaSobre = new TelaSobre();

        }

        telaSobre.setVisible(true);
        
        
    }//GEN-LAST:event_btnSobreActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // 
        
        int option = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?","Atenção",JOptionPane.YES_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {

            conecta.desconecta();

            if (telaLoadEnd == null) {

                telaLoadEnd = new TelaLoadEnd();

            }

            telaLoadEnd.setVisible(true);

        }
        
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaHome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendamento;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSobre;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel fundoHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtBoasVindas;
    private javax.swing.JLabel txtDataHome;
    private javax.swing.JLabel txtHoraHome;
    private javax.swing.JLabel txtUsuarioLogado;
    // End of variables declaration//GEN-END:variables

    
    
    class hora implements ActionListener {
        
        @Override
        public void actionPerformed (ActionEvent e) {
            
            Calendar now = Calendar.getInstance();
            txtHoraHome.setText(String.format("%1$tH:%1$tM:%1$tS", now));
            
        }
        
    }
    
    
    
    
 // FIM DO FORMULÁRIO   
}
